### ISSUE TITLE
Performance on other datasets

### ISSUE THREAD

**Issue by zyxforever** [monniert/dti-clustering#1]
Thank you for sharing codes, could you show the performance on other datasets such as CIFAR10 and STL?

**Comment by monniert** [comment]
Thanks for your interest in the project! Because we don't model transformations to go from a specific object type to another inside a same class (e.g. from an eagle to a pigeon for the bird class), the method is not yet designed to work on such datasets. So we have not evaluated on them but I suspect the performances will be poor
